from ._core import (
    DataRecord,
    DataRecordGraphQL,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    GraphQLCore,
    GraphQLList,
    ResourcesWrite,
    ResourcesWriteResult,
    PageInfo,
    TimeSeriesGraphQL,
)
from ._equipment_module import (
    EquipmentModule,
    EquipmentModuleApply,
    EquipmentModuleApplyList,
    EquipmentModuleFields,
    EquipmentModuleGraphQL,
    EquipmentModuleList,
    EquipmentModuleTextFields,
    EquipmentModuleWrite,
    EquipmentModuleWriteList,
)
from ._start_end_time import (
    StartEndTime,
    StartEndTimeApply,
    StartEndTimeApplyList,
    StartEndTimeFields,
    StartEndTimeGraphQL,
    StartEndTimeList,
    StartEndTimeWrite,
    StartEndTimeWriteList,
)
from ._unit_procedure import (
    UnitProcedure,
    UnitProcedureApply,
    UnitProcedureApplyList,
    UnitProcedureFields,
    UnitProcedureGraphQL,
    UnitProcedureList,
    UnitProcedureTextFields,
    UnitProcedureWrite,
    UnitProcedureWriteList,
)
from ._work_order import (
    WorkOrder,
    WorkOrderApply,
    WorkOrderApplyList,
    WorkOrderFields,
    WorkOrderGraphQL,
    WorkOrderList,
    WorkOrderTextFields,
    WorkOrderWrite,
    WorkOrderWriteList,
)


EquipmentModuleGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

UnitProcedure.update_forward_refs(
    StartEndTime=StartEndTime,
)
UnitProcedureGraphQL.update_forward_refs(
    StartEndTimeGraphQL=StartEndTimeGraphQL,
)
UnitProcedureWrite.update_forward_refs(
    StartEndTimeWrite=StartEndTimeWrite,
)
UnitProcedureApply.update_forward_refs(
    StartEndTimeWrite=StartEndTimeWrite,
)

StartEndTime.update_forward_refs(
    EquipmentModule=EquipmentModule,
    WorkOrder=WorkOrder,
)
StartEndTimeGraphQL.update_forward_refs(
    EquipmentModuleGraphQL=EquipmentModuleGraphQL,
    WorkOrderGraphQL=WorkOrderGraphQL,
)
StartEndTimeWrite.update_forward_refs(
    EquipmentModuleWrite=EquipmentModuleWrite,
    WorkOrderWrite=WorkOrderWrite,
)
StartEndTimeApply.update_forward_refs(
    EquipmentModuleWrite=EquipmentModuleWrite,
    WorkOrderWrite=WorkOrderWrite,
)


__all__ = [
    "DataRecord",
    "DataRecordGraphQL",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "GraphQLCore",
    "GraphQLList",
    "ResourcesWriteResult",
    "PageInfo",
    "TimeSeriesGraphQL",
    "EquipmentModule",
    "EquipmentModuleGraphQL",
    "EquipmentModuleWrite",
    "EquipmentModuleApply",
    "EquipmentModuleList",
    "EquipmentModuleWriteList",
    "EquipmentModuleApplyList",
    "EquipmentModuleFields",
    "EquipmentModuleTextFields",
    "StartEndTime",
    "StartEndTimeGraphQL",
    "StartEndTimeWrite",
    "StartEndTimeApply",
    "StartEndTimeList",
    "StartEndTimeWriteList",
    "StartEndTimeApplyList",
    "StartEndTimeFields",
    "UnitProcedure",
    "UnitProcedureGraphQL",
    "UnitProcedureWrite",
    "UnitProcedureApply",
    "UnitProcedureList",
    "UnitProcedureWriteList",
    "UnitProcedureApplyList",
    "UnitProcedureFields",
    "UnitProcedureTextFields",
    "WorkOrder",
    "WorkOrderGraphQL",
    "WorkOrderWrite",
    "WorkOrderApply",
    "WorkOrderList",
    "WorkOrderWriteList",
    "WorkOrderApplyList",
    "WorkOrderFields",
    "WorkOrderTextFields",
]
