environment:
  name: dev
  project: python-pygen
  type: dev
  selected:
  - modules/

variables:
  modules:
    models:
      omni:
        pygen_models_space: sp_pygen_models
        pygen_other_models_space: sp_pygen_models_other
      wind:
        pygen_power: sp_pygen_power
        pygen_power_enterprise: sp_pygen_power_enterprise

      cdf_idm_extension:
        organization: YourOrg
        schema_space: sp_enterprise_min_schema_idm

    cdf_ingestion:
      workflow: ingestion
      groupSourceId: fc008a26-40e8-4a4c-a357-2d914fbd9873
      ingestionClientId: ${INGESTION_CLIENT_ID}
      ingestionClientSecret: ${INGESTION_CLIENT_SECRET}
      assetTransformationExternalId: sap_assets_springfield_s4hana
      equipmentTransformationExternalId: sap_equipment_springfield_s4hana
      assetToAssetTransformationExternalId: sap_asset_to_asset_springfield_s4hana
      equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
      timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
      maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
      operationTransformationExternalId: sap_operations_springfield_s4hana
      operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
      fileTransformationExternalId: files_metadata_springfield
      activityToAssetTransformationExternalId: activity_to_asset
      activityToEquipmentTransformationExternalId: activity_to_equipment
      activityToTimeSeriesTransformationExternalId: activity_to_timeseries
      timeSeriesToAssetTransformationExternalId: timeseries_to_asset
      timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
      pandidContextualizationFunction: contextualization_p_and_id_annotater
      contextualization_connection_writer: contextualization_connection_writer
      dataset: ingestion
      rawSourceDatabase: ingestion
      rawStateDatabase: contextualizationState
      schemaSpace: cdf_cdm
      schemaSpace2: cdf_idm
      instanceSpaces:
      - springfield_instances
      - cdf_cdm_units

    industrial_tools:
      cdf_search:
        location: springfield
        locationName: Springfield
        instanceSpace: springfield_instances

    sourcesystem:
      cdf_pi:
        sourceName: Springfield AVEVA PI
        sourceId: springfield_aveva_pi
        timeseriesTransformationExternalId: pi_timeseries_springfield_aveva_pi
        dataset: ingestion
        rawSourceDatabase: ingestion
        schemaSpace: cdf_cdm
        instanceSpace: springfield_instances

      cdf_sap_assets:
        sourceName: SAP Springfield S/4HANA Assets
        sourceId: sap_springfield_s4hana_assets
        assetTransformationExternalId: sap_assets_springfield_s4hana
        equipmentTransformationExternalId: sap_equipment_springfield_s4hana
        assetToAssetTransformationExternalId: sap_asset_to_asset_springfield_s4hana
        equipmentToAssetTransformationExternalId: sap_equipment_to_asset_springfield_s4hana
        dataset: ingestion
        rawSourceDatabase: ingestion
        schemaSpace: cdf_cdm
        instanceSpace: springfield_instances

      cdf_sap_events:
        sourceName: SAP Springfield S/4HANA Activities
        sourceId: sap_springfield_s4hana_activities
        maintenanceOrderTransformationExternalId: sap_maintenance_orders_springfield_s4hana
        operationTransformationExternalId: sap_operations_springfield_s4hana
        operationToMaintenanceOrderTransformationExternalId: sap_operation_to_maintenance_order_springfield_s4hana
        dataset: ingestion
        rawSourceDatabase: ingestion
        schemaSpace2: cdf_idm
        instanceSpace: springfield_instances

      cdf_sharepoint:
        sourceName: Springfield Sharepoint
        sourceId: springfield_sharepoint
        fileTransformationExternalId: files_metadata_springfield
        dataset: ingestion
        rawSourceDatabase: ingestion
        schemaSpace: cdf_cdm
        instanceSpace: springfield_instances

    contextualization:
      cdf_connection_sql:
        activityToAssetTransformationExternalId: activity_to_asset
        activityToEquipmentTransformationExternalId: activity_to_equipment
        activityToTimeSeriesTransformationExternalId: activity_to_timeseries
        timeSeriesToAssetTransformationExternalId: timeseries_to_asset
        timeSeriesToEquipmentTransformationExternalId: timeseries_to_equipment
        dataset: ingestion
        instanceSpace: springfield_instances
        schemaSpace: cdf_cdm

      cdf_p_and_id_parser:
        contextualizationId: p_and_id_parser
        contextualizationName: P&ID Parser
        annotatorJob: ctx_files_pandid_annotater
        directRelationJob: ctx_files_direct_relation_write
        dataset: ingestion
        rawStateDatabase: contextualizationState
        rawStateTable: diagramParsing
        schemaSpace: cdf_cdm
        annotationSpace: springfield_instances
        instanceSpaces:
        - springfield_instances

