site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: material
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - Changelog: CHANGELOG.md

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
