site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: material
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - CLI: cli.md
    - Experiment in Notebook: notebook.ipynb
    - Examples: examples/movie_domain.ipynb
    - Changelog: CHANGELOG.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list


plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
