site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: "material"
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - Quickstart:
        - CDF Hosted Notebook: quickstart/cdf_notebook.ipynb
        - Local Notebook: quickstart/notebook.ipynb
        - Python Application: quickstart/project.md
    - Installation: installation.md
    - CLI: cli.md
    - Examples: examples/movie_domain.ipynb
    - API:
        - Pygen: api/api.md
        - Demo: api/demo.md
        - Exceptions: api/exceptions.md
        - Utilities:
            - CDF: api/utils_cdf.md
            - Text: api/utils_text.md
    - Changelog: CHANGELOG.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
