site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: material
    logo: logo/logo.svg
    favicon: logo/logo.svg
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - What is Pygen?: what_is_pygen.md
    - Quickstart:
        - Where to Start: quickstart/where_to_start.md
        - Exploration CDF Notebook: quickstart/cdf_notebook.ipynb
        - Exploration Local Notebook: quickstart/notebook.ipynb
        - Building Solution: quickstart/project.md
        - Building Solution CDF Streamlit: quickstart/cdf_streamlit.md
        - Data Population (Ingestion): quickstart/ingestion.ipynb
        - Data Migration: quickstart/migration.ipynb
    - Installation: installation.md
    - CLI: cli.md
    - Usage:
        - Generation of SDK: usage/generation.ipynb
        - Listing, filtering, and retrieving: usage/listing_filtering_retrieving.ipynb
        - Searching: usage/searching.ipynb
        - Aggregation: usage/aggregation.ipynb
        - Querying: usage/querying.ipynb
        - Creating and Deleting: usage/creating_deleting.ipynb
        - Working with Time Series: usage/timeseries.ipynb
        - Working with Edges: usage/edge_properties.ipynb
    - Extra:
        - Generating Mock Data: extra/mock_data.ipynb
    - Pygen Config:
        - Home: config/index.md
        - Naming: config/naming.md
        - Filtering: config/filtering_methods.md
    - API:
        - Pygen: api/api.md
        - Demo: api/demo.md
        - Exceptions: api/exceptions.md
        - Utilities:
            - Main: api/utils.md
            - CDF: api/utils_cdf.md
            - Mock Generator: api/utils_mock_generator.md
            - Text: api/utils_text.md
            - ExternalID Factories: api/utils_external_id_factory.md
    - Changelog: CHANGELOG.md
    - Developer Docs:
        - Home: developer_docs/index.md
        - Core:
            - Generators: developer_docs/core/generators.md
            - Models:
                - APIClasses: developer_docs/core/models/api_classes.md
                - DataClasses: developer_docs/core/models/data_classes.md
                - Fields:
                    - developer_docs/core/models/fields/base.md
                    - developer_docs/core/models/fields/primitive.md
                    - developer_docs/core/models/fields/cdf_reference.md
                    - developer_docs/core/models/fields/connection.md
                - FilterMethods: developer_docs/core/models/filter_methods.md
            - Validation: developer_docs/core/validation.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
      remove_tag_config:
        remove_input_tags:
          - hide

  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
  - search
exclude_docs: |
  .*
  examples/movie_domain/.*
