site_name: Pygen Docs
docs_dir: docs
use_directory_urls: false
theme:
    name: "material"
    features:
      - content.code.copy
      - content.tooltips

nav:
    - Home: index.md
    - Quickstart:
        - Where to Start: quickstart/where_to_start.md
        - Exploration CDF Notebook: quickstart/cdf_notebook.ipynb
        - Exploration Local Notebook: quickstart/notebook.ipynb
        - Building Solution: quickstart/project.md
        - Data Population (Ingestion): quickstart/ingestion.ipynb
        - Data Migration: quickstart/migration.ipynb
    - Installation: installation.md
    - CLI: cli.md
    - Examples:
        - Movie: examples/movie_domain.ipynb
        - Working with Time Series: examples/timeseries.ipynb
    - Pygen Config:
        - Home: config/index.md
        - Naming: config/naming.md
        - Filtering: config/filtering_methods.md
    - API:
        - Pygen: api/api.md
        - Demo: api/demo.md
        - Exceptions: api/exceptions.md
        - Utilities:
            - CDF: api/utils_cdf.md
            - Text: api/utils_text.md
            - ExternalID Factories: api/utils_external_id_factory.md
    - Changelog: CHANGELOG.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      execute: false
      ignore_h1_titles: True
      include_source: True
      remove_tag_config:
        remove_input_tags:
          - hide

  - glightbox:
       width: 100%
       height: auto
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
  - search
exclude_docs: |
  .*
  examples/movie_domain/.*
