from cognite_core.data_classes._core import (
    DataRecord,
    DataRecordGraphQL,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelList,
    DomainModelWrite,
    DomainRelationWrite,
    FileMetadataGraphQL,
    GraphQLCore,
    GraphQLList,
    PageInfo,
    ResourcesWrite,
    ResourcesWriteResult,
    SequenceColumnGraphQL,
    SequenceGraphQL,
    TimeSeriesGraphQL,
)

from ._cognite_3_d_model import (
    Cognite3DModel,
    Cognite3DModelApply,
    Cognite3DModelApplyList,
    Cognite3DModelFields,
    Cognite3DModelGraphQL,
    Cognite3DModelList,
    Cognite3DModelTextFields,
    Cognite3DModelWrite,
    Cognite3DModelWriteList,
)
from ._cognite_3_d_object import (
    Cognite3DObject,
    Cognite3DObjectApply,
    Cognite3DObjectApplyList,
    Cognite3DObjectFields,
    Cognite3DObjectGraphQL,
    Cognite3DObjectList,
    Cognite3DObjectTextFields,
    Cognite3DObjectWrite,
    Cognite3DObjectWriteList,
)
from ._cognite_3_d_revision import (
    Cognite3DRevision,
    Cognite3DRevisionApply,
    Cognite3DRevisionApplyList,
    Cognite3DRevisionFields,
    Cognite3DRevisionGraphQL,
    Cognite3DRevisionList,
    Cognite3DRevisionTextFields,
    Cognite3DRevisionWrite,
    Cognite3DRevisionWriteList,
)
from ._cognite_3_d_transformation_edge import (
    Cognite3DTransformationEdge,
    Cognite3DTransformationEdgeApply,
    Cognite3DTransformationEdgeApplyList,
    Cognite3DTransformationEdgeFields,
    Cognite3DTransformationEdgeGraphQL,
    Cognite3DTransformationEdgeList,
    Cognite3DTransformationEdgeTextFields,
    Cognite3DTransformationEdgeWrite,
    Cognite3DTransformationEdgeWriteList,
)
from ._cognite_3_d_transformation_node import (
    Cognite3DTransformationNode,
    Cognite3DTransformationNodeApply,
    Cognite3DTransformationNodeApplyList,
    Cognite3DTransformationNodeFields,
    Cognite3DTransformationNodeGraphQL,
    Cognite3DTransformationNodeList,
    Cognite3DTransformationNodeTextFields,
    Cognite3DTransformationNodeWrite,
    Cognite3DTransformationNodeWriteList,
)
from ._cognite_360_image import (
    Cognite360Image,
    Cognite360ImageApply,
    Cognite360ImageApplyList,
    Cognite360ImageFields,
    Cognite360ImageGraphQL,
    Cognite360ImageList,
    Cognite360ImageTextFields,
    Cognite360ImageWrite,
    Cognite360ImageWriteList,
)
from ._cognite_360_image_annotation import (
    Cognite360ImageAnnotation,
    Cognite360ImageAnnotationApply,
    Cognite360ImageAnnotationApplyList,
    Cognite360ImageAnnotationFields,
    Cognite360ImageAnnotationGraphQL,
    Cognite360ImageAnnotationList,
    Cognite360ImageAnnotationTextFields,
    Cognite360ImageAnnotationWrite,
    Cognite360ImageAnnotationWriteList,
)
from ._cognite_360_image_collection import (
    Cognite360ImageCollection,
    Cognite360ImageCollectionApply,
    Cognite360ImageCollectionApplyList,
    Cognite360ImageCollectionFields,
    Cognite360ImageCollectionGraphQL,
    Cognite360ImageCollectionList,
    Cognite360ImageCollectionTextFields,
    Cognite360ImageCollectionWrite,
    Cognite360ImageCollectionWriteList,
)
from ._cognite_360_image_model import (
    Cognite360ImageModel,
    Cognite360ImageModelApply,
    Cognite360ImageModelApplyList,
    Cognite360ImageModelFields,
    Cognite360ImageModelGraphQL,
    Cognite360ImageModelList,
    Cognite360ImageModelTextFields,
    Cognite360ImageModelWrite,
    Cognite360ImageModelWriteList,
)
from ._cognite_360_image_station import (
    Cognite360ImageStation,
    Cognite360ImageStationApply,
    Cognite360ImageStationApplyList,
    Cognite360ImageStationFields,
    Cognite360ImageStationGraphQL,
    Cognite360ImageStationList,
    Cognite360ImageStationTextFields,
    Cognite360ImageStationWrite,
    Cognite360ImageStationWriteList,
)
from ._cognite_activity import (
    CogniteActivity,
    CogniteActivityApply,
    CogniteActivityApplyList,
    CogniteActivityFields,
    CogniteActivityGraphQL,
    CogniteActivityList,
    CogniteActivityTextFields,
    CogniteActivityWrite,
    CogniteActivityWriteList,
)
from ._cognite_annotation import (
    CogniteAnnotation,
    CogniteAnnotationApply,
    CogniteAnnotationApplyList,
    CogniteAnnotationFields,
    CogniteAnnotationGraphQL,
    CogniteAnnotationList,
    CogniteAnnotationTextFields,
    CogniteAnnotationWrite,
    CogniteAnnotationWriteList,
)
from ._cognite_asset import (
    CogniteAsset,
    CogniteAssetApply,
    CogniteAssetApplyList,
    CogniteAssetFields,
    CogniteAssetGraphQL,
    CogniteAssetList,
    CogniteAssetTextFields,
    CogniteAssetWrite,
    CogniteAssetWriteList,
)
from ._cognite_asset_class import (
    CogniteAssetClass,
    CogniteAssetClassApply,
    CogniteAssetClassApplyList,
    CogniteAssetClassFields,
    CogniteAssetClassGraphQL,
    CogniteAssetClassList,
    CogniteAssetClassTextFields,
    CogniteAssetClassWrite,
    CogniteAssetClassWriteList,
)
from ._cognite_asset_type import (
    CogniteAssetType,
    CogniteAssetTypeApply,
    CogniteAssetTypeApplyList,
    CogniteAssetTypeFields,
    CogniteAssetTypeGraphQL,
    CogniteAssetTypeList,
    CogniteAssetTypeTextFields,
    CogniteAssetTypeWrite,
    CogniteAssetTypeWriteList,
)
from ._cognite_cad_model import (
    CogniteCADModel,
    CogniteCADModelApply,
    CogniteCADModelApplyList,
    CogniteCADModelFields,
    CogniteCADModelGraphQL,
    CogniteCADModelList,
    CogniteCADModelTextFields,
    CogniteCADModelWrite,
    CogniteCADModelWriteList,
)
from ._cognite_cad_node import (
    CogniteCADNode,
    CogniteCADNodeApply,
    CogniteCADNodeApplyList,
    CogniteCADNodeFields,
    CogniteCADNodeGraphQL,
    CogniteCADNodeList,
    CogniteCADNodeTextFields,
    CogniteCADNodeWrite,
    CogniteCADNodeWriteList,
)
from ._cognite_cad_revision import (
    CogniteCADRevision,
    CogniteCADRevisionApply,
    CogniteCADRevisionApplyList,
    CogniteCADRevisionFields,
    CogniteCADRevisionGraphQL,
    CogniteCADRevisionList,
    CogniteCADRevisionTextFields,
    CogniteCADRevisionWrite,
    CogniteCADRevisionWriteList,
)
from ._cognite_cube_map import (
    CogniteCubeMap,
    CogniteCubeMapApply,
    CogniteCubeMapApplyList,
    CogniteCubeMapFields,
    CogniteCubeMapGraphQL,
    CogniteCubeMapList,
    CogniteCubeMapTextFields,
    CogniteCubeMapWrite,
    CogniteCubeMapWriteList,
)
from ._cognite_describable_edge import (
    CogniteDescribableEdge,
    CogniteDescribableEdgeApply,
    CogniteDescribableEdgeApplyList,
    CogniteDescribableEdgeFields,
    CogniteDescribableEdgeGraphQL,
    CogniteDescribableEdgeList,
    CogniteDescribableEdgeTextFields,
    CogniteDescribableEdgeWrite,
    CogniteDescribableEdgeWriteList,
)
from ._cognite_describable_node import (
    CogniteDescribableNode,
    CogniteDescribableNodeApply,
    CogniteDescribableNodeApplyList,
    CogniteDescribableNodeFields,
    CogniteDescribableNodeGraphQL,
    CogniteDescribableNodeList,
    CogniteDescribableNodeTextFields,
    CogniteDescribableNodeWrite,
    CogniteDescribableNodeWriteList,
)
from ._cognite_diagram_annotation import (
    CogniteDiagramAnnotation,
    CogniteDiagramAnnotationApply,
    CogniteDiagramAnnotationApplyList,
    CogniteDiagramAnnotationFields,
    CogniteDiagramAnnotationGraphQL,
    CogniteDiagramAnnotationList,
    CogniteDiagramAnnotationTextFields,
    CogniteDiagramAnnotationWrite,
    CogniteDiagramAnnotationWriteList,
)
from ._cognite_equipment import (
    CogniteEquipment,
    CogniteEquipmentApply,
    CogniteEquipmentApplyList,
    CogniteEquipmentFields,
    CogniteEquipmentGraphQL,
    CogniteEquipmentList,
    CogniteEquipmentTextFields,
    CogniteEquipmentWrite,
    CogniteEquipmentWriteList,
)
from ._cognite_equipment_type import (
    CogniteEquipmentType,
    CogniteEquipmentTypeApply,
    CogniteEquipmentTypeApplyList,
    CogniteEquipmentTypeFields,
    CogniteEquipmentTypeGraphQL,
    CogniteEquipmentTypeList,
    CogniteEquipmentTypeTextFields,
    CogniteEquipmentTypeWrite,
    CogniteEquipmentTypeWriteList,
)
from ._cognite_file import (
    CogniteFile,
    CogniteFileApply,
    CogniteFileApplyList,
    CogniteFileFields,
    CogniteFileGraphQL,
    CogniteFileList,
    CogniteFileTextFields,
    CogniteFileWrite,
    CogniteFileWriteList,
)
from ._cognite_file_category import (
    CogniteFileCategory,
    CogniteFileCategoryApply,
    CogniteFileCategoryApplyList,
    CogniteFileCategoryFields,
    CogniteFileCategoryGraphQL,
    CogniteFileCategoryList,
    CogniteFileCategoryTextFields,
    CogniteFileCategoryWrite,
    CogniteFileCategoryWriteList,
)
from ._cognite_point_cloud_model import (
    CognitePointCloudModel,
    CognitePointCloudModelApply,
    CognitePointCloudModelApplyList,
    CognitePointCloudModelFields,
    CognitePointCloudModelGraphQL,
    CognitePointCloudModelList,
    CognitePointCloudModelTextFields,
    CognitePointCloudModelWrite,
    CognitePointCloudModelWriteList,
)
from ._cognite_point_cloud_revision import (
    CognitePointCloudRevision,
    CognitePointCloudRevisionApply,
    CognitePointCloudRevisionApplyList,
    CognitePointCloudRevisionFields,
    CognitePointCloudRevisionGraphQL,
    CognitePointCloudRevisionList,
    CognitePointCloudRevisionTextFields,
    CognitePointCloudRevisionWrite,
    CognitePointCloudRevisionWriteList,
)
from ._cognite_point_cloud_volume import (
    CognitePointCloudVolume,
    CognitePointCloudVolumeApply,
    CognitePointCloudVolumeApplyList,
    CognitePointCloudVolumeFields,
    CognitePointCloudVolumeGraphQL,
    CognitePointCloudVolumeList,
    CognitePointCloudVolumeTextFields,
    CognitePointCloudVolumeWrite,
    CognitePointCloudVolumeWriteList,
)
from ._cognite_schedulable import (
    CogniteSchedulable,
    CogniteSchedulableApply,
    CogniteSchedulableApplyList,
    CogniteSchedulableFields,
    CogniteSchedulableGraphQL,
    CogniteSchedulableList,
    CogniteSchedulableTextFields,
    CogniteSchedulableWrite,
    CogniteSchedulableWriteList,
)
from ._cognite_source_system import (
    CogniteSourceSystem,
    CogniteSourceSystemApply,
    CogniteSourceSystemApplyList,
    CogniteSourceSystemFields,
    CogniteSourceSystemGraphQL,
    CogniteSourceSystemList,
    CogniteSourceSystemTextFields,
    CogniteSourceSystemWrite,
    CogniteSourceSystemWriteList,
)
from ._cognite_sourceable_edge import (
    CogniteSourceableEdge,
    CogniteSourceableEdgeApply,
    CogniteSourceableEdgeApplyList,
    CogniteSourceableEdgeFields,
    CogniteSourceableEdgeGraphQL,
    CogniteSourceableEdgeList,
    CogniteSourceableEdgeTextFields,
    CogniteSourceableEdgeWrite,
    CogniteSourceableEdgeWriteList,
)
from ._cognite_sourceable_node import (
    CogniteSourceableNode,
    CogniteSourceableNodeApply,
    CogniteSourceableNodeApplyList,
    CogniteSourceableNodeFields,
    CogniteSourceableNodeGraphQL,
    CogniteSourceableNodeList,
    CogniteSourceableNodeTextFields,
    CogniteSourceableNodeWrite,
    CogniteSourceableNodeWriteList,
)
from ._cognite_time_series import (
    CogniteTimeSeries,
    CogniteTimeSeriesApply,
    CogniteTimeSeriesApplyList,
    CogniteTimeSeriesFields,
    CogniteTimeSeriesGraphQL,
    CogniteTimeSeriesList,
    CogniteTimeSeriesTextFields,
    CogniteTimeSeriesWrite,
    CogniteTimeSeriesWriteList,
)
from ._cognite_unit import (
    CogniteUnit,
    CogniteUnitApply,
    CogniteUnitApplyList,
    CogniteUnitFields,
    CogniteUnitGraphQL,
    CogniteUnitList,
    CogniteUnitTextFields,
    CogniteUnitWrite,
    CogniteUnitWriteList,
)
from ._cognite_visualizable import (
    CogniteVisualizable,
    CogniteVisualizableApply,
    CogniteVisualizableApplyList,
    CogniteVisualizableFields,
    CogniteVisualizableGraphQL,
    CogniteVisualizableList,
    CogniteVisualizableTextFields,
    CogniteVisualizableWrite,
    CogniteVisualizableWriteList,
)

Cognite360Image.model_rebuild()
Cognite360ImageGraphQL.model_rebuild()
Cognite360ImageWrite.model_rebuild()
Cognite360ImageApply.model_rebuild()
Cognite360ImageCollection.model_rebuild()
Cognite360ImageCollectionGraphQL.model_rebuild()
Cognite360ImageCollectionWrite.model_rebuild()
Cognite360ImageCollectionApply.model_rebuild()
Cognite360ImageModel.model_rebuild()
Cognite360ImageModelGraphQL.model_rebuild()
Cognite360ImageModelWrite.model_rebuild()
Cognite360ImageModelApply.model_rebuild()
Cognite3DModel.model_rebuild()
Cognite3DModelGraphQL.model_rebuild()
Cognite3DModelWrite.model_rebuild()
Cognite3DModelApply.model_rebuild()
Cognite3DObject.model_rebuild()
Cognite3DObjectGraphQL.model_rebuild()
Cognite3DObjectWrite.model_rebuild()
Cognite3DObjectApply.model_rebuild()
Cognite3DRevision.model_rebuild()
Cognite3DRevisionGraphQL.model_rebuild()
Cognite3DRevisionWrite.model_rebuild()
Cognite3DRevisionApply.model_rebuild()
CogniteActivity.model_rebuild()
CogniteActivityGraphQL.model_rebuild()
CogniteActivityWrite.model_rebuild()
CogniteActivityApply.model_rebuild()
CogniteAsset.model_rebuild()
CogniteAssetGraphQL.model_rebuild()
CogniteAssetWrite.model_rebuild()
CogniteAssetApply.model_rebuild()
CogniteAssetType.model_rebuild()
CogniteAssetTypeGraphQL.model_rebuild()
CogniteAssetTypeWrite.model_rebuild()
CogniteAssetTypeApply.model_rebuild()
CogniteCADModel.model_rebuild()
CogniteCADModelGraphQL.model_rebuild()
CogniteCADModelWrite.model_rebuild()
CogniteCADModelApply.model_rebuild()
CogniteCADNode.model_rebuild()
CogniteCADNodeGraphQL.model_rebuild()
CogniteCADNodeWrite.model_rebuild()
CogniteCADNodeApply.model_rebuild()
CogniteCADRevision.model_rebuild()
CogniteCADRevisionGraphQL.model_rebuild()
CogniteCADRevisionWrite.model_rebuild()
CogniteCADRevisionApply.model_rebuild()
CogniteCubeMap.model_rebuild()
CogniteCubeMapGraphQL.model_rebuild()
CogniteCubeMapWrite.model_rebuild()
CogniteCubeMapApply.model_rebuild()
CogniteEquipment.model_rebuild()
CogniteEquipmentGraphQL.model_rebuild()
CogniteEquipmentWrite.model_rebuild()
CogniteEquipmentApply.model_rebuild()
CogniteFile.model_rebuild()
CogniteFileGraphQL.model_rebuild()
CogniteFileWrite.model_rebuild()
CogniteFileApply.model_rebuild()
CognitePointCloudModel.model_rebuild()
CognitePointCloudModelGraphQL.model_rebuild()
CognitePointCloudModelWrite.model_rebuild()
CognitePointCloudModelApply.model_rebuild()
CognitePointCloudRevision.model_rebuild()
CognitePointCloudRevisionGraphQL.model_rebuild()
CognitePointCloudRevisionWrite.model_rebuild()
CognitePointCloudRevisionApply.model_rebuild()
CognitePointCloudVolume.model_rebuild()
CognitePointCloudVolumeGraphQL.model_rebuild()
CognitePointCloudVolumeWrite.model_rebuild()
CognitePointCloudVolumeApply.model_rebuild()
CogniteSourceableNode.model_rebuild()
CogniteSourceableNodeGraphQL.model_rebuild()
CogniteSourceableNodeWrite.model_rebuild()
CogniteSourceableNodeApply.model_rebuild()
CogniteTimeSeries.model_rebuild()
CogniteTimeSeriesGraphQL.model_rebuild()
CogniteTimeSeriesWrite.model_rebuild()
CogniteTimeSeriesApply.model_rebuild()
CogniteVisualizable.model_rebuild()
CogniteVisualizableGraphQL.model_rebuild()
CogniteVisualizableWrite.model_rebuild()
CogniteVisualizableApply.model_rebuild()
Cognite360ImageAnnotation.model_rebuild()
Cognite360ImageAnnotationGraphQL.model_rebuild()
Cognite360ImageAnnotationWrite.model_rebuild()
Cognite360ImageAnnotationApply.model_rebuild()
CogniteAnnotation.model_rebuild()
CogniteAnnotationGraphQL.model_rebuild()
CogniteAnnotationWrite.model_rebuild()
CogniteAnnotationApply.model_rebuild()
CogniteDiagramAnnotation.model_rebuild()
CogniteDiagramAnnotationGraphQL.model_rebuild()
CogniteDiagramAnnotationWrite.model_rebuild()
CogniteDiagramAnnotationApply.model_rebuild()
CogniteSourceableEdge.model_rebuild()
CogniteSourceableEdgeGraphQL.model_rebuild()
CogniteSourceableEdgeWrite.model_rebuild()
CogniteSourceableEdgeApply.model_rebuild()


__all__ = [
    "DataRecord",
    "DataRecordGraphQL",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "GraphQLCore",
    "GraphQLList",
    "ResourcesWriteResult",
    "PageInfo",
    "TimeSeriesGraphQL",
    "FileMetadataGraphQL",
    "SequenceColumnGraphQL",
    "SequenceGraphQL",
    "Cognite360Image",
    "Cognite360ImageGraphQL",
    "Cognite360ImageWrite",
    "Cognite360ImageApply",
    "Cognite360ImageList",
    "Cognite360ImageWriteList",
    "Cognite360ImageApplyList",
    "Cognite360ImageFields",
    "Cognite360ImageTextFields",
    "Cognite360ImageAnnotation",
    "Cognite360ImageAnnotationGraphQL",
    "Cognite360ImageAnnotationWrite",
    "Cognite360ImageAnnotationApply",
    "Cognite360ImageAnnotationList",
    "Cognite360ImageAnnotationWriteList",
    "Cognite360ImageAnnotationApplyList",
    "Cognite360ImageAnnotationFields",
    "Cognite360ImageAnnotationTextFields",
    "Cognite360ImageCollection",
    "Cognite360ImageCollectionGraphQL",
    "Cognite360ImageCollectionWrite",
    "Cognite360ImageCollectionApply",
    "Cognite360ImageCollectionList",
    "Cognite360ImageCollectionWriteList",
    "Cognite360ImageCollectionApplyList",
    "Cognite360ImageCollectionFields",
    "Cognite360ImageCollectionTextFields",
    "Cognite360ImageModel",
    "Cognite360ImageModelGraphQL",
    "Cognite360ImageModelWrite",
    "Cognite360ImageModelApply",
    "Cognite360ImageModelList",
    "Cognite360ImageModelWriteList",
    "Cognite360ImageModelApplyList",
    "Cognite360ImageModelFields",
    "Cognite360ImageModelTextFields",
    "Cognite360ImageStation",
    "Cognite360ImageStationGraphQL",
    "Cognite360ImageStationWrite",
    "Cognite360ImageStationApply",
    "Cognite360ImageStationList",
    "Cognite360ImageStationWriteList",
    "Cognite360ImageStationApplyList",
    "Cognite360ImageStationFields",
    "Cognite360ImageStationTextFields",
    "Cognite3DModel",
    "Cognite3DModelGraphQL",
    "Cognite3DModelWrite",
    "Cognite3DModelApply",
    "Cognite3DModelList",
    "Cognite3DModelWriteList",
    "Cognite3DModelApplyList",
    "Cognite3DModelFields",
    "Cognite3DModelTextFields",
    "Cognite3DObject",
    "Cognite3DObjectGraphQL",
    "Cognite3DObjectWrite",
    "Cognite3DObjectApply",
    "Cognite3DObjectList",
    "Cognite3DObjectWriteList",
    "Cognite3DObjectApplyList",
    "Cognite3DObjectFields",
    "Cognite3DObjectTextFields",
    "Cognite3DRevision",
    "Cognite3DRevisionGraphQL",
    "Cognite3DRevisionWrite",
    "Cognite3DRevisionApply",
    "Cognite3DRevisionList",
    "Cognite3DRevisionWriteList",
    "Cognite3DRevisionApplyList",
    "Cognite3DRevisionFields",
    "Cognite3DRevisionTextFields",
    "Cognite3DTransformationEdge",
    "Cognite3DTransformationEdgeGraphQL",
    "Cognite3DTransformationEdgeWrite",
    "Cognite3DTransformationEdgeApply",
    "Cognite3DTransformationEdgeList",
    "Cognite3DTransformationEdgeWriteList",
    "Cognite3DTransformationEdgeApplyList",
    "Cognite3DTransformationEdgeFields",
    "Cognite3DTransformationEdgeTextFields",
    "Cognite3DTransformationNode",
    "Cognite3DTransformationNodeGraphQL",
    "Cognite3DTransformationNodeWrite",
    "Cognite3DTransformationNodeApply",
    "Cognite3DTransformationNodeList",
    "Cognite3DTransformationNodeWriteList",
    "Cognite3DTransformationNodeApplyList",
    "Cognite3DTransformationNodeFields",
    "Cognite3DTransformationNodeTextFields",
    "CogniteActivity",
    "CogniteActivityGraphQL",
    "CogniteActivityWrite",
    "CogniteActivityApply",
    "CogniteActivityList",
    "CogniteActivityWriteList",
    "CogniteActivityApplyList",
    "CogniteActivityFields",
    "CogniteActivityTextFields",
    "CogniteAnnotation",
    "CogniteAnnotationGraphQL",
    "CogniteAnnotationWrite",
    "CogniteAnnotationApply",
    "CogniteAnnotationList",
    "CogniteAnnotationWriteList",
    "CogniteAnnotationApplyList",
    "CogniteAnnotationFields",
    "CogniteAnnotationTextFields",
    "CogniteAsset",
    "CogniteAssetGraphQL",
    "CogniteAssetWrite",
    "CogniteAssetApply",
    "CogniteAssetList",
    "CogniteAssetWriteList",
    "CogniteAssetApplyList",
    "CogniteAssetFields",
    "CogniteAssetTextFields",
    "CogniteAssetClass",
    "CogniteAssetClassGraphQL",
    "CogniteAssetClassWrite",
    "CogniteAssetClassApply",
    "CogniteAssetClassList",
    "CogniteAssetClassWriteList",
    "CogniteAssetClassApplyList",
    "CogniteAssetClassFields",
    "CogniteAssetClassTextFields",
    "CogniteAssetType",
    "CogniteAssetTypeGraphQL",
    "CogniteAssetTypeWrite",
    "CogniteAssetTypeApply",
    "CogniteAssetTypeList",
    "CogniteAssetTypeWriteList",
    "CogniteAssetTypeApplyList",
    "CogniteAssetTypeFields",
    "CogniteAssetTypeTextFields",
    "CogniteCADModel",
    "CogniteCADModelGraphQL",
    "CogniteCADModelWrite",
    "CogniteCADModelApply",
    "CogniteCADModelList",
    "CogniteCADModelWriteList",
    "CogniteCADModelApplyList",
    "CogniteCADModelFields",
    "CogniteCADModelTextFields",
    "CogniteCADNode",
    "CogniteCADNodeGraphQL",
    "CogniteCADNodeWrite",
    "CogniteCADNodeApply",
    "CogniteCADNodeList",
    "CogniteCADNodeWriteList",
    "CogniteCADNodeApplyList",
    "CogniteCADNodeFields",
    "CogniteCADNodeTextFields",
    "CogniteCADRevision",
    "CogniteCADRevisionGraphQL",
    "CogniteCADRevisionWrite",
    "CogniteCADRevisionApply",
    "CogniteCADRevisionList",
    "CogniteCADRevisionWriteList",
    "CogniteCADRevisionApplyList",
    "CogniteCADRevisionFields",
    "CogniteCADRevisionTextFields",
    "CogniteCubeMap",
    "CogniteCubeMapGraphQL",
    "CogniteCubeMapWrite",
    "CogniteCubeMapApply",
    "CogniteCubeMapList",
    "CogniteCubeMapWriteList",
    "CogniteCubeMapApplyList",
    "CogniteCubeMapFields",
    "CogniteCubeMapTextFields",
    "CogniteDescribableEdge",
    "CogniteDescribableEdgeGraphQL",
    "CogniteDescribableEdgeWrite",
    "CogniteDescribableEdgeApply",
    "CogniteDescribableEdgeList",
    "CogniteDescribableEdgeWriteList",
    "CogniteDescribableEdgeApplyList",
    "CogniteDescribableEdgeFields",
    "CogniteDescribableEdgeTextFields",
    "CogniteDescribableNode",
    "CogniteDescribableNodeGraphQL",
    "CogniteDescribableNodeWrite",
    "CogniteDescribableNodeApply",
    "CogniteDescribableNodeList",
    "CogniteDescribableNodeWriteList",
    "CogniteDescribableNodeApplyList",
    "CogniteDescribableNodeFields",
    "CogniteDescribableNodeTextFields",
    "CogniteDiagramAnnotation",
    "CogniteDiagramAnnotationGraphQL",
    "CogniteDiagramAnnotationWrite",
    "CogniteDiagramAnnotationApply",
    "CogniteDiagramAnnotationList",
    "CogniteDiagramAnnotationWriteList",
    "CogniteDiagramAnnotationApplyList",
    "CogniteDiagramAnnotationFields",
    "CogniteDiagramAnnotationTextFields",
    "CogniteEquipment",
    "CogniteEquipmentGraphQL",
    "CogniteEquipmentWrite",
    "CogniteEquipmentApply",
    "CogniteEquipmentList",
    "CogniteEquipmentWriteList",
    "CogniteEquipmentApplyList",
    "CogniteEquipmentFields",
    "CogniteEquipmentTextFields",
    "CogniteEquipmentType",
    "CogniteEquipmentTypeGraphQL",
    "CogniteEquipmentTypeWrite",
    "CogniteEquipmentTypeApply",
    "CogniteEquipmentTypeList",
    "CogniteEquipmentTypeWriteList",
    "CogniteEquipmentTypeApplyList",
    "CogniteEquipmentTypeFields",
    "CogniteEquipmentTypeTextFields",
    "CogniteFile",
    "CogniteFileGraphQL",
    "CogniteFileWrite",
    "CogniteFileApply",
    "CogniteFileList",
    "CogniteFileWriteList",
    "CogniteFileApplyList",
    "CogniteFileFields",
    "CogniteFileTextFields",
    "CogniteFileCategory",
    "CogniteFileCategoryGraphQL",
    "CogniteFileCategoryWrite",
    "CogniteFileCategoryApply",
    "CogniteFileCategoryList",
    "CogniteFileCategoryWriteList",
    "CogniteFileCategoryApplyList",
    "CogniteFileCategoryFields",
    "CogniteFileCategoryTextFields",
    "CognitePointCloudModel",
    "CognitePointCloudModelGraphQL",
    "CognitePointCloudModelWrite",
    "CognitePointCloudModelApply",
    "CognitePointCloudModelList",
    "CognitePointCloudModelWriteList",
    "CognitePointCloudModelApplyList",
    "CognitePointCloudModelFields",
    "CognitePointCloudModelTextFields",
    "CognitePointCloudRevision",
    "CognitePointCloudRevisionGraphQL",
    "CognitePointCloudRevisionWrite",
    "CognitePointCloudRevisionApply",
    "CognitePointCloudRevisionList",
    "CognitePointCloudRevisionWriteList",
    "CognitePointCloudRevisionApplyList",
    "CognitePointCloudRevisionFields",
    "CognitePointCloudRevisionTextFields",
    "CognitePointCloudVolume",
    "CognitePointCloudVolumeGraphQL",
    "CognitePointCloudVolumeWrite",
    "CognitePointCloudVolumeApply",
    "CognitePointCloudVolumeList",
    "CognitePointCloudVolumeWriteList",
    "CognitePointCloudVolumeApplyList",
    "CognitePointCloudVolumeFields",
    "CognitePointCloudVolumeTextFields",
    "CogniteSchedulable",
    "CogniteSchedulableGraphQL",
    "CogniteSchedulableWrite",
    "CogniteSchedulableApply",
    "CogniteSchedulableList",
    "CogniteSchedulableWriteList",
    "CogniteSchedulableApplyList",
    "CogniteSchedulableFields",
    "CogniteSchedulableTextFields",
    "CogniteSourceSystem",
    "CogniteSourceSystemGraphQL",
    "CogniteSourceSystemWrite",
    "CogniteSourceSystemApply",
    "CogniteSourceSystemList",
    "CogniteSourceSystemWriteList",
    "CogniteSourceSystemApplyList",
    "CogniteSourceSystemFields",
    "CogniteSourceSystemTextFields",
    "CogniteSourceableEdge",
    "CogniteSourceableEdgeGraphQL",
    "CogniteSourceableEdgeWrite",
    "CogniteSourceableEdgeApply",
    "CogniteSourceableEdgeList",
    "CogniteSourceableEdgeWriteList",
    "CogniteSourceableEdgeApplyList",
    "CogniteSourceableEdgeFields",
    "CogniteSourceableEdgeTextFields",
    "CogniteSourceableNode",
    "CogniteSourceableNodeGraphQL",
    "CogniteSourceableNodeWrite",
    "CogniteSourceableNodeApply",
    "CogniteSourceableNodeList",
    "CogniteSourceableNodeWriteList",
    "CogniteSourceableNodeApplyList",
    "CogniteSourceableNodeFields",
    "CogniteSourceableNodeTextFields",
    "CogniteTimeSeries",
    "CogniteTimeSeriesGraphQL",
    "CogniteTimeSeriesWrite",
    "CogniteTimeSeriesApply",
    "CogniteTimeSeriesList",
    "CogniteTimeSeriesWriteList",
    "CogniteTimeSeriesApplyList",
    "CogniteTimeSeriesFields",
    "CogniteTimeSeriesTextFields",
    "CogniteUnit",
    "CogniteUnitGraphQL",
    "CogniteUnitWrite",
    "CogniteUnitApply",
    "CogniteUnitList",
    "CogniteUnitWriteList",
    "CogniteUnitApplyList",
    "CogniteUnitFields",
    "CogniteUnitTextFields",
    "CogniteVisualizable",
    "CogniteVisualizableGraphQL",
    "CogniteVisualizableWrite",
    "CogniteVisualizableApply",
    "CogniteVisualizableList",
    "CogniteVisualizableWriteList",
    "CogniteVisualizableApplyList",
    "CogniteVisualizableFields",
    "CogniteVisualizableTextFields",
]
