space: {{ schema_space }}
externalId: {{ organization }}ProcessIndustries
name: {{ organization }} enterprise model
description: {{ organization }} enterprise model
version: v1
views:
- space: {{ schema_space }}
  externalId: {{ organization }}MaintenanceOrder
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Operation
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Notification
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}SourceSystem
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Sourceable
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Asset
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}AssetClass
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}AssetType
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Equipment
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}EquipmentType
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}File
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}FileCategory
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Activity
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}TimeSeries
  version: v1
  type: view
- space: {{ schema_space }}
  externalId: {{ organization }}Unit
  version: v1
  type: view
