from ._core import (
    DataRecord,
    DataRecordGraphQL,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    GraphQLCore,
    GraphQLList,
    ResourcesWrite,
    ResourcesWriteResult,
    PageInfo,
    TimeSeriesGraphQL,
)
from ._connection_item_a import (
    ConnectionItemA,
    ConnectionItemAApply,
    ConnectionItemAApplyList,
    ConnectionItemAFields,
    ConnectionItemAGraphQL,
    ConnectionItemAList,
    ConnectionItemATextFields,
    ConnectionItemAWrite,
    ConnectionItemAWriteList,
)
from ._connection_item_b import (
    ConnectionItemB,
    ConnectionItemBApply,
    ConnectionItemBApplyList,
    ConnectionItemBFields,
    ConnectionItemBGraphQL,
    ConnectionItemBList,
    ConnectionItemBTextFields,
    ConnectionItemBWrite,
    ConnectionItemBWriteList,
)
from ._connection_item_c_edge import (
    ConnectionItemCEdge,
    ConnectionItemCEdgeFields,
    ConnectionItemCEdgeGraphQL,
    ConnectionItemCEdgeList,
    ConnectionItemCEdgeTextFields,
)
from ._connection_item_c_node import (
    ConnectionItemCNode,
    ConnectionItemCNodeApply,
    ConnectionItemCNodeApplyList,
    ConnectionItemCNodeFields,
    ConnectionItemCNodeGraphQL,
    ConnectionItemCNodeList,
    ConnectionItemCNodeTextFields,
    ConnectionItemCNodeWrite,
    ConnectionItemCNodeWriteList,
)


ConnectionItemA.update_forward_refs(
    ConnectionItemA=ConnectionItemA,
    ConnectionItemB=ConnectionItemB,
    ConnectionItemCNode=ConnectionItemCNode,
)
ConnectionItemAGraphQL.update_forward_refs(
    ConnectionItemAGraphQL=ConnectionItemAGraphQL,
    ConnectionItemBGraphQL=ConnectionItemBGraphQL,
    ConnectionItemCNodeGraphQL=ConnectionItemCNodeGraphQL,
)
ConnectionItemAWrite.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
    ConnectionItemCNodeWrite=ConnectionItemCNodeWrite,
)
ConnectionItemAApply.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
    ConnectionItemCNodeWrite=ConnectionItemCNodeWrite,
)

ConnectionItemB.update_forward_refs(
    ConnectionItemA=ConnectionItemA,
    ConnectionItemB=ConnectionItemB,
)
ConnectionItemBGraphQL.update_forward_refs(
    ConnectionItemAGraphQL=ConnectionItemAGraphQL,
    ConnectionItemBGraphQL=ConnectionItemBGraphQL,
)
ConnectionItemBWrite.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
)
ConnectionItemBApply.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
)

ConnectionItemCNode.update_forward_refs(
    ConnectionItemA=ConnectionItemA,
    ConnectionItemB=ConnectionItemB,
)
ConnectionItemCNodeGraphQL.update_forward_refs(
    ConnectionItemAGraphQL=ConnectionItemAGraphQL,
    ConnectionItemBGraphQL=ConnectionItemBGraphQL,
)
ConnectionItemCNodeWrite.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
)
ConnectionItemCNodeApply.update_forward_refs(
    ConnectionItemAWrite=ConnectionItemAWrite,
    ConnectionItemBWrite=ConnectionItemBWrite,
)

ConnectionItemCEdge.update_forward_refs(
    ConnectionItemA=ConnectionItemA,
    ConnectionItemB=ConnectionItemB,
)
ConnectionItemCEdgeGraphQL.update_forward_refs(
    ConnectionItemAGraphQL=ConnectionItemAGraphQL,
    ConnectionItemBGraphQL=ConnectionItemBGraphQL,
)


__all__ = [
    "DataRecord",
    "DataRecordGraphQL",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "GraphQLCore",
    "GraphQLList",
    "ResourcesWriteResult",
    "PageInfo",
    "TimeSeriesGraphQL",
    "ConnectionItemA",
    "ConnectionItemAGraphQL",
    "ConnectionItemAWrite",
    "ConnectionItemAApply",
    "ConnectionItemAList",
    "ConnectionItemAWriteList",
    "ConnectionItemAApplyList",
    "ConnectionItemAFields",
    "ConnectionItemATextFields",
    "ConnectionItemB",
    "ConnectionItemBGraphQL",
    "ConnectionItemBWrite",
    "ConnectionItemBApply",
    "ConnectionItemBList",
    "ConnectionItemBWriteList",
    "ConnectionItemBApplyList",
    "ConnectionItemBFields",
    "ConnectionItemBTextFields",
    "ConnectionItemCEdge",
    "ConnectionItemCEdgeGraphQL",
    "ConnectionItemCEdgeList",
    "ConnectionItemCEdgeFields",
    "ConnectionItemCEdgeTextFields",
    "ConnectionItemCNode",
    "ConnectionItemCNodeGraphQL",
    "ConnectionItemCNodeWrite",
    "ConnectionItemCNodeApply",
    "ConnectionItemCNodeList",
    "ConnectionItemCNodeWriteList",
    "ConnectionItemCNodeApplyList",
    "ConnectionItemCNodeFields",
    "ConnectionItemCNodeTextFields",
]
