from ._core import (
    DataRecord,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    ResourcesWrite,
    ResourcesWriteResult,
)
from ._blade import Blade, BladeFields, BladeList, BladeTextFields, BladeWrite, BladeWriteList
from ._gearbox import Gearbox, GearboxFields, GearboxList, GearboxWrite, GearboxWriteList
from ._generator import Generator, GeneratorFields, GeneratorList, GeneratorWrite, GeneratorWriteList
from ._high_speed_shaft import (
    HighSpeedShaft,
    HighSpeedShaftFields,
    HighSpeedShaftList,
    HighSpeedShaftWrite,
    HighSpeedShaftWriteList,
)
from ._main_shaft import MainShaft, MainShaftFields, MainShaftList, MainShaftWrite, MainShaftWriteList
from ._metmast import Metmast, MetmastFields, MetmastList, MetmastWrite, MetmastWriteList
from ._nacelle import Nacelle, NacelleFields, NacelleList, NacelleWrite, NacelleWriteList
from ._power_inverter import (
    PowerInverter,
    PowerInverterFields,
    PowerInverterList,
    PowerInverterWrite,
    PowerInverterWriteList,
)
from ._rotor import Rotor, RotorFields, RotorList, RotorWrite, RotorWriteList
from ._sensor_position import (
    SensorPosition,
    SensorPositionFields,
    SensorPositionList,
    SensorPositionWrite,
    SensorPositionWriteList,
)
from ._windmill import Windmill, WindmillFields, WindmillList, WindmillTextFields, WindmillWrite, WindmillWriteList

Blade.model_rebuild()
BladeWrite.model_rebuild()
Nacelle.model_rebuild()
NacelleWrite.model_rebuild()
Windmill.model_rebuild()
WindmillWrite.model_rebuild()

__all__ = [
    "DataRecord",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "ResourcesWriteResult",
    "Blade",
    "BladeWrite",
    "BladeApply",
    "BladeList",
    "BladeWriteList",
    "BladeApplyList",
    "BladeFields",
    "BladeTextFields",
    "Gearbox",
    "GearboxWrite",
    "GearboxApply",
    "GearboxList",
    "GearboxWriteList",
    "GearboxApplyList",
    "GearboxFields",
    "Generator",
    "GeneratorWrite",
    "GeneratorApply",
    "GeneratorList",
    "GeneratorWriteList",
    "GeneratorApplyList",
    "GeneratorFields",
    "HighSpeedShaft",
    "HighSpeedShaftWrite",
    "HighSpeedShaftApply",
    "HighSpeedShaftList",
    "HighSpeedShaftWriteList",
    "HighSpeedShaftApplyList",
    "HighSpeedShaftFields",
    "MainShaft",
    "MainShaftWrite",
    "MainShaftApply",
    "MainShaftList",
    "MainShaftWriteList",
    "MainShaftApplyList",
    "MainShaftFields",
    "Metmast",
    "MetmastWrite",
    "MetmastApply",
    "MetmastList",
    "MetmastWriteList",
    "MetmastApplyList",
    "MetmastFields",
    "Nacelle",
    "NacelleWrite",
    "NacelleApply",
    "NacelleList",
    "NacelleWriteList",
    "NacelleApplyList",
    "NacelleFields",
    "PowerInverter",
    "PowerInverterWrite",
    "PowerInverterApply",
    "PowerInverterList",
    "PowerInverterWriteList",
    "PowerInverterApplyList",
    "PowerInverterFields",
    "Rotor",
    "RotorWrite",
    "RotorApply",
    "RotorList",
    "RotorWriteList",
    "RotorApplyList",
    "RotorFields",
    "SensorPosition",
    "SensorPositionWrite",
    "SensorPositionApply",
    "SensorPositionList",
    "SensorPositionWriteList",
    "SensorPositionApplyList",
    "SensorPositionFields",
    "Windmill",
    "WindmillWrite",
    "WindmillApply",
    "WindmillList",
    "WindmillWriteList",
    "WindmillApplyList",
    "WindmillFields",
    "WindmillTextFields",
]
