from ._core import (
    DataRecord,
    DataRecordGraphQL,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    GraphQLCore,
    GraphQLList,
    ResourcesWrite,
    ResourcesWriteResult,
    PageInfo,
    TimeSeriesGraphQL,
)
from ._blade import (
    Blade,
    BladeApply,
    BladeApplyList,
    BladeFields,
    BladeGraphQL,
    BladeList,
    BladeTextFields,
    BladeWrite,
    BladeWriteList,
)
from ._gearbox import (
    Gearbox,
    GearboxApply,
    GearboxApplyList,
    GearboxFields,
    GearboxGraphQL,
    GearboxList,
    GearboxWrite,
    GearboxWriteList,
)
from ._generator import (
    Generator,
    GeneratorApply,
    GeneratorApplyList,
    GeneratorFields,
    GeneratorGraphQL,
    GeneratorList,
    GeneratorWrite,
    GeneratorWriteList,
)
from ._high_speed_shaft import (
    HighSpeedShaft,
    HighSpeedShaftApply,
    HighSpeedShaftApplyList,
    HighSpeedShaftFields,
    HighSpeedShaftGraphQL,
    HighSpeedShaftList,
    HighSpeedShaftWrite,
    HighSpeedShaftWriteList,
)
from ._main_shaft import (
    MainShaft,
    MainShaftApply,
    MainShaftApplyList,
    MainShaftFields,
    MainShaftGraphQL,
    MainShaftList,
    MainShaftWrite,
    MainShaftWriteList,
)
from ._metmast import (
    Metmast,
    MetmastApply,
    MetmastApplyList,
    MetmastFields,
    MetmastGraphQL,
    MetmastList,
    MetmastWrite,
    MetmastWriteList,
)
from ._nacelle import (
    Nacelle,
    NacelleApply,
    NacelleApplyList,
    NacelleFields,
    NacelleGraphQL,
    NacelleList,
    NacelleWrite,
    NacelleWriteList,
)
from ._power_inverter import (
    PowerInverter,
    PowerInverterApply,
    PowerInverterApplyList,
    PowerInverterFields,
    PowerInverterGraphQL,
    PowerInverterList,
    PowerInverterWrite,
    PowerInverterWriteList,
)
from ._rotor import Rotor, RotorApply, RotorApplyList, RotorFields, RotorGraphQL, RotorList, RotorWrite, RotorWriteList
from ._sensor_position import (
    SensorPosition,
    SensorPositionApply,
    SensorPositionApplyList,
    SensorPositionFields,
    SensorPositionGraphQL,
    SensorPositionList,
    SensorPositionWrite,
    SensorPositionWriteList,
)
from ._windmill import (
    Windmill,
    WindmillApply,
    WindmillApplyList,
    WindmillFields,
    WindmillGraphQL,
    WindmillList,
    WindmillTextFields,
    WindmillWrite,
    WindmillWriteList,
)

Blade.model_rebuild()
BladeGraphQL.model_rebuild()
BladeWrite.model_rebuild()
BladeApply.model_rebuild()
Gearbox.model_rebuild()
GearboxGraphQL.model_rebuild()
GearboxWrite.model_rebuild()
GearboxApply.model_rebuild()
Generator.model_rebuild()
GeneratorGraphQL.model_rebuild()
GeneratorWrite.model_rebuild()
GeneratorApply.model_rebuild()
HighSpeedShaft.model_rebuild()
HighSpeedShaftGraphQL.model_rebuild()
HighSpeedShaftWrite.model_rebuild()
HighSpeedShaftApply.model_rebuild()
MainShaft.model_rebuild()
MainShaftGraphQL.model_rebuild()
MainShaftWrite.model_rebuild()
MainShaftApply.model_rebuild()
Metmast.model_rebuild()
MetmastGraphQL.model_rebuild()
MetmastWrite.model_rebuild()
MetmastApply.model_rebuild()
Nacelle.model_rebuild()
NacelleGraphQL.model_rebuild()
NacelleWrite.model_rebuild()
NacelleApply.model_rebuild()
PowerInverter.model_rebuild()
PowerInverterGraphQL.model_rebuild()
PowerInverterWrite.model_rebuild()
PowerInverterApply.model_rebuild()
Rotor.model_rebuild()
RotorGraphQL.model_rebuild()
RotorWrite.model_rebuild()
RotorApply.model_rebuild()
SensorPosition.model_rebuild()
SensorPositionGraphQL.model_rebuild()
SensorPositionWrite.model_rebuild()
SensorPositionApply.model_rebuild()
Windmill.model_rebuild()
WindmillGraphQL.model_rebuild()
WindmillWrite.model_rebuild()
WindmillApply.model_rebuild()


__all__ = [
    "DataRecord",
    "DataRecordGraphQL",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "GraphQLCore",
    "GraphQLList",
    "ResourcesWriteResult",
    "PageInfo",
    "TimeSeriesGraphQL",
    "Blade",
    "BladeGraphQL",
    "BladeWrite",
    "BladeApply",
    "BladeList",
    "BladeWriteList",
    "BladeApplyList",
    "BladeFields",
    "BladeTextFields",
    "Gearbox",
    "GearboxGraphQL",
    "GearboxWrite",
    "GearboxApply",
    "GearboxList",
    "GearboxWriteList",
    "GearboxApplyList",
    "GearboxFields",
    "Generator",
    "GeneratorGraphQL",
    "GeneratorWrite",
    "GeneratorApply",
    "GeneratorList",
    "GeneratorWriteList",
    "GeneratorApplyList",
    "GeneratorFields",
    "HighSpeedShaft",
    "HighSpeedShaftGraphQL",
    "HighSpeedShaftWrite",
    "HighSpeedShaftApply",
    "HighSpeedShaftList",
    "HighSpeedShaftWriteList",
    "HighSpeedShaftApplyList",
    "HighSpeedShaftFields",
    "MainShaft",
    "MainShaftGraphQL",
    "MainShaftWrite",
    "MainShaftApply",
    "MainShaftList",
    "MainShaftWriteList",
    "MainShaftApplyList",
    "MainShaftFields",
    "Metmast",
    "MetmastGraphQL",
    "MetmastWrite",
    "MetmastApply",
    "MetmastList",
    "MetmastWriteList",
    "MetmastApplyList",
    "MetmastFields",
    "Nacelle",
    "NacelleGraphQL",
    "NacelleWrite",
    "NacelleApply",
    "NacelleList",
    "NacelleWriteList",
    "NacelleApplyList",
    "NacelleFields",
    "PowerInverter",
    "PowerInverterGraphQL",
    "PowerInverterWrite",
    "PowerInverterApply",
    "PowerInverterList",
    "PowerInverterWriteList",
    "PowerInverterApplyList",
    "PowerInverterFields",
    "Rotor",
    "RotorGraphQL",
    "RotorWrite",
    "RotorApply",
    "RotorList",
    "RotorWriteList",
    "RotorApplyList",
    "RotorFields",
    "SensorPosition",
    "SensorPositionGraphQL",
    "SensorPositionWrite",
    "SensorPositionApply",
    "SensorPositionList",
    "SensorPositionWriteList",
    "SensorPositionApplyList",
    "SensorPositionFields",
    "Windmill",
    "WindmillGraphQL",
    "WindmillWrite",
    "WindmillApply",
    "WindmillList",
    "WindmillWriteList",
    "WindmillApplyList",
    "WindmillFields",
    "WindmillTextFields",
]
