from ._core import (
    DataRecord,
    DataRecordGraphQL,
    DataRecordWrite,
    DomainModel,
    DomainModelCore,
    DomainModelWrite,
    DomainModelList,
    DomainRelationWrite,
    GraphQLCore,
    GraphQLList,
    ResourcesWrite,
    ResourcesWriteResult,
    PageInfo,
    TimeSeriesGraphQL,
    FileMetadataGraphQL,
    SequenceColumnGraphQL,
    SequenceGraphQL,
)
from ._blade import (
    Blade,
    BladeApply,
    BladeApplyList,
    BladeFields,
    BladeGraphQL,
    BladeList,
    BladeTextFields,
    BladeWrite,
    BladeWriteList,
)
from ._gearbox import (
    Gearbox,
    GearboxApply,
    GearboxApplyList,
    GearboxFields,
    GearboxGraphQL,
    GearboxList,
    GearboxTextFields,
    GearboxWrite,
    GearboxWriteList,
)
from ._generator import (
    Generator,
    GeneratorApply,
    GeneratorApplyList,
    GeneratorFields,
    GeneratorGraphQL,
    GeneratorList,
    GeneratorTextFields,
    GeneratorWrite,
    GeneratorWriteList,
)
from ._high_speed_shaft import (
    HighSpeedShaft,
    HighSpeedShaftApply,
    HighSpeedShaftApplyList,
    HighSpeedShaftFields,
    HighSpeedShaftGraphQL,
    HighSpeedShaftList,
    HighSpeedShaftTextFields,
    HighSpeedShaftWrite,
    HighSpeedShaftWriteList,
)
from ._main_shaft import (
    MainShaft,
    MainShaftApply,
    MainShaftApplyList,
    MainShaftFields,
    MainShaftGraphQL,
    MainShaftList,
    MainShaftTextFields,
    MainShaftWrite,
    MainShaftWriteList,
)
from ._metmast import (
    Metmast,
    MetmastApply,
    MetmastApplyList,
    MetmastFields,
    MetmastGraphQL,
    MetmastList,
    MetmastTextFields,
    MetmastWrite,
    MetmastWriteList,
)
from ._nacelle import (
    Nacelle,
    NacelleApply,
    NacelleApplyList,
    NacelleFields,
    NacelleGraphQL,
    NacelleList,
    NacelleTextFields,
    NacelleWrite,
    NacelleWriteList,
)
from ._power_inverter import (
    PowerInverter,
    PowerInverterApply,
    PowerInverterApplyList,
    PowerInverterFields,
    PowerInverterGraphQL,
    PowerInverterList,
    PowerInverterTextFields,
    PowerInverterWrite,
    PowerInverterWriteList,
)
from ._rotor import (
    Rotor,
    RotorApply,
    RotorApplyList,
    RotorFields,
    RotorGraphQL,
    RotorList,
    RotorTextFields,
    RotorWrite,
    RotorWriteList,
)
from ._sensor_position import (
    SensorPosition,
    SensorPositionApply,
    SensorPositionApplyList,
    SensorPositionFields,
    SensorPositionGraphQL,
    SensorPositionList,
    SensorPositionTextFields,
    SensorPositionWrite,
    SensorPositionWriteList,
)
from ._windmill import (
    Windmill,
    WindmillApply,
    WindmillApplyList,
    WindmillFields,
    WindmillGraphQL,
    WindmillList,
    WindmillTextFields,
    WindmillWrite,
    WindmillWriteList,
)


Blade.update_forward_refs(
    SensorPosition=SensorPosition,
)
BladeGraphQL.update_forward_refs(
    SensorPositionGraphQL=SensorPositionGraphQL,
)
BladeWrite.update_forward_refs(
    SensorPositionWrite=SensorPositionWrite,
)
BladeApply.update_forward_refs(
    SensorPositionWrite=SensorPositionWrite,
)

GearboxGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

GeneratorGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

HighSpeedShaftGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

MainShaftGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

MetmastGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

Nacelle.update_forward_refs(
    Gearbox=Gearbox,
    Generator=Generator,
    HighSpeedShaft=HighSpeedShaft,
    MainShaft=MainShaft,
    PowerInverter=PowerInverter,
)
NacelleGraphQL.update_forward_refs(
    GearboxGraphQL=GearboxGraphQL,
    GeneratorGraphQL=GeneratorGraphQL,
    HighSpeedShaftGraphQL=HighSpeedShaftGraphQL,
    MainShaftGraphQL=MainShaftGraphQL,
    PowerInverterGraphQL=PowerInverterGraphQL,
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)
NacelleWrite.update_forward_refs(
    GearboxWrite=GearboxWrite,
    GeneratorWrite=GeneratorWrite,
    HighSpeedShaftWrite=HighSpeedShaftWrite,
    MainShaftWrite=MainShaftWrite,
    PowerInverterWrite=PowerInverterWrite,
)
NacelleApply.update_forward_refs(
    GearboxWrite=GearboxWrite,
    GeneratorWrite=GeneratorWrite,
    HighSpeedShaftWrite=HighSpeedShaftWrite,
    MainShaftWrite=MainShaftWrite,
    PowerInverterWrite=PowerInverterWrite,
)

PowerInverterGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

RotorGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

SensorPositionGraphQL.update_forward_refs(
    TimeSeriesGraphQL=TimeSeriesGraphQL,
)

Windmill.update_forward_refs(
    Blade=Blade,
    Metmast=Metmast,
    Nacelle=Nacelle,
    Rotor=Rotor,
)
WindmillGraphQL.update_forward_refs(
    BladeGraphQL=BladeGraphQL,
    MetmastGraphQL=MetmastGraphQL,
    NacelleGraphQL=NacelleGraphQL,
    RotorGraphQL=RotorGraphQL,
)
WindmillWrite.update_forward_refs(
    BladeWrite=BladeWrite,
    MetmastWrite=MetmastWrite,
    NacelleWrite=NacelleWrite,
    RotorWrite=RotorWrite,
)
WindmillApply.update_forward_refs(
    BladeWrite=BladeWrite,
    MetmastWrite=MetmastWrite,
    NacelleWrite=NacelleWrite,
    RotorWrite=RotorWrite,
)


__all__ = [
    "DataRecord",
    "DataRecordGraphQL",
    "DataRecordWrite",
    "ResourcesWrite",
    "DomainModel",
    "DomainModelCore",
    "DomainModelWrite",
    "DomainModelList",
    "DomainRelationWrite",
    "GraphQLCore",
    "GraphQLList",
    "ResourcesWriteResult",
    "PageInfo",
    "TimeSeriesGraphQL",
    "FileMetadataGraphQL",
    "SequenceColumnGraphQL",
    "SequenceGraphQL",
    "Blade",
    "BladeGraphQL",
    "BladeWrite",
    "BladeApply",
    "BladeList",
    "BladeWriteList",
    "BladeApplyList",
    "BladeFields",
    "BladeTextFields",
    "Gearbox",
    "GearboxGraphQL",
    "GearboxWrite",
    "GearboxApply",
    "GearboxList",
    "GearboxWriteList",
    "GearboxApplyList",
    "GearboxFields",
    "GearboxTextFields",
    "Generator",
    "GeneratorGraphQL",
    "GeneratorWrite",
    "GeneratorApply",
    "GeneratorList",
    "GeneratorWriteList",
    "GeneratorApplyList",
    "GeneratorFields",
    "GeneratorTextFields",
    "HighSpeedShaft",
    "HighSpeedShaftGraphQL",
    "HighSpeedShaftWrite",
    "HighSpeedShaftApply",
    "HighSpeedShaftList",
    "HighSpeedShaftWriteList",
    "HighSpeedShaftApplyList",
    "HighSpeedShaftFields",
    "HighSpeedShaftTextFields",
    "MainShaft",
    "MainShaftGraphQL",
    "MainShaftWrite",
    "MainShaftApply",
    "MainShaftList",
    "MainShaftWriteList",
    "MainShaftApplyList",
    "MainShaftFields",
    "MainShaftTextFields",
    "Metmast",
    "MetmastGraphQL",
    "MetmastWrite",
    "MetmastApply",
    "MetmastList",
    "MetmastWriteList",
    "MetmastApplyList",
    "MetmastFields",
    "MetmastTextFields",
    "Nacelle",
    "NacelleGraphQL",
    "NacelleWrite",
    "NacelleApply",
    "NacelleList",
    "NacelleWriteList",
    "NacelleApplyList",
    "NacelleFields",
    "NacelleTextFields",
    "PowerInverter",
    "PowerInverterGraphQL",
    "PowerInverterWrite",
    "PowerInverterApply",
    "PowerInverterList",
    "PowerInverterWriteList",
    "PowerInverterApplyList",
    "PowerInverterFields",
    "PowerInverterTextFields",
    "Rotor",
    "RotorGraphQL",
    "RotorWrite",
    "RotorApply",
    "RotorList",
    "RotorWriteList",
    "RotorApplyList",
    "RotorFields",
    "RotorTextFields",
    "SensorPosition",
    "SensorPositionGraphQL",
    "SensorPositionWrite",
    "SensorPositionApply",
    "SensorPositionList",
    "SensorPositionWriteList",
    "SensorPositionApplyList",
    "SensorPositionFields",
    "SensorPositionTextFields",
    "Windmill",
    "WindmillGraphQL",
    "WindmillWrite",
    "WindmillApply",
    "WindmillList",
    "WindmillWriteList",
    "WindmillApplyList",
    "WindmillFields",
    "WindmillTextFields",
]
